export const ON_NEW_MESSAGE_CREATED = 'ON_NEW_MESSAGE_CREATED';
export const ON_NEW_MESSAGE_THREAD_CREATED = 'ON_NEW_MESSAGE_THREAD_CREATED';
export const ON_MESSAGE_UPDATE = 'ON_MESSAGE_UPDATE';
export const ON_CALL_START = 'ON_CALL_START';
export const ON_ICE_CANDIDATE = 'ON_ICE_CANDIDATE';
export const ON_CALL_ANSWER = 'ON_CALL_ANSWER';